version: "3.7"
services:

  traefik:
    image: traefik:v2.1
    restart: unless-stopped
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Exposed for backend access via LAN
    networks:
      - web
    volumes:
      - ./traefik.yml:/traefik.yml
      - ./dynamic_conf.yml:/dynamic_conf.yml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=dashboard"
      - "traefik.frontend.rule=Host:dashboard.traefik.moritzvd.com"
      - "traefik.port=8080"

  whoami:
    image: containous/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-secure.entrypoints=https"
      - "traefik.http.routers.whoami-secure.rule=Host(`whoami.traefik.moritzvd.com`)"
      - "traefik.http.routers.whoami-secure.tls.certresolver=myhttpchallenge"

  httpd:
    image: httpd:alpine
    container_name: httpd
    restart: unless-stopped
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs/
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.httpd-secure.entrypoints=https"
      - "traefik.http.routers.httpd-secure.rule=Host(`traefik.moritzvd.com`)"
      - "traefik.http.routers.httpd-secure.middlewares=httpd-security"
      - "traefik.http.routers.httpd-secure.tls.certresolver=myhttpchallenge"
      - "traefik.http.middlewares.httpd-security.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.httpd-security.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.httpd-security.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.httpd-security.headers.frameDeny=true"
      - "traefik.http.middlewares.httpd-security.headers.SSLHost=traefik.moritzvd.com"
      - "traefik.http.middlewares.httpd-security.headers.SSLRedirect=true"
      - "traefik.http.middlewares.httpd-security.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.httpd-security.headers.STSSeconds=63072000"

networks:
  web:
    name: web
    driver: bridge
